/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDashboardModelsRouteImport } from './routes/_authed/dashboard/models'
import { Route as AuthedDashboardInboxRouteImport } from './routes/_authed/dashboard/inbox'
import { Route as marketingauthSignUpIndexRouteImport } from './routes/(marketing)/(auth)/sign-up/index'
import { Route as marketingauthSignInIndexRouteImport } from './routes/(marketing)/(auth)/sign-in/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardModelsRoute = AuthedDashboardModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardInboxRoute = AuthedDashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const marketingauthSignUpIndexRoute =
  marketingauthSignUpIndexRouteImport.update({
    id: '/(auth)/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => marketingRouteRoute,
  } as any)
const marketingauthSignInIndexRoute =
  marketingauthSignInIndexRouteImport.update({
    id: '/(auth)/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => marketingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/dashboard/inbox': typeof AuthedDashboardInboxRoute
  '/dashboard/models': typeof AuthedDashboardModelsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/sign-in/': typeof marketingauthSignInIndexRoute
  '/sign-up/': typeof marketingauthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/dashboard/inbox': typeof AuthedDashboardInboxRoute
  '/dashboard/models': typeof AuthedDashboardModelsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/sign-in': typeof marketingauthSignInIndexRoute
  '/sign-up': typeof marketingauthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/(marketing)/': typeof marketingIndexRoute
  '/_authed/dashboard/inbox': typeof AuthedDashboardInboxRoute
  '/_authed/dashboard/models': typeof AuthedDashboardModelsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/(marketing)/(auth)/sign-in/': typeof marketingauthSignInIndexRoute
  '/(marketing)/(auth)/sign-up/': typeof marketingauthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/inbox'
    | '/dashboard/models'
    | '/api/auth/$'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/inbox'
    | '/dashboard/models'
    | '/api/auth/$'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/(marketing)'
    | '/_authed'
    | '/_authed/dashboard'
    | '/(marketing)/'
    | '/_authed/dashboard/inbox'
    | '/_authed/dashboard/models'
    | '/api/auth/$'
    | '/_authed/dashboard/'
    | '/(marketing)/(auth)/sign-in/'
    | '/(marketing)/(auth)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/models': {
      id: '/_authed/dashboard/models'
      path: '/models'
      fullPath: '/dashboard/models'
      preLoaderRoute: typeof AuthedDashboardModelsRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/inbox': {
      id: '/_authed/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof AuthedDashboardInboxRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/(marketing)/(auth)/sign-up/': {
      id: '/(marketing)/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof marketingauthSignUpIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/(auth)/sign-in/': {
      id: '/(marketing)/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof marketingauthSignInIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
  marketingauthSignInIndexRoute: typeof marketingauthSignInIndexRoute
  marketingauthSignUpIndexRoute: typeof marketingauthSignUpIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
  marketingauthSignInIndexRoute: marketingauthSignInIndexRoute,
  marketingauthSignUpIndexRoute: marketingauthSignUpIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardInboxRoute: typeof AuthedDashboardInboxRoute
  AuthedDashboardModelsRoute: typeof AuthedDashboardModelsRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardInboxRoute: AuthedDashboardInboxRoute,
  AuthedDashboardModelsRoute: AuthedDashboardModelsRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
